// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "specChart.h"

void Analyzer::cb_Start_i(Fl_Button*, void*) {
  process(this);
}
void Analyzer::cb_Start(Fl_Button* o, void* v) {
  ((Analyzer*)(o->parent()->user_data()))->cb_Start_i(o,v);
}

Analyzer::Analyzer() {
  { specWindow = new Fl_Double_Window(869, 443);
    specWindow->user_data((void*)(this));
    { chart = new Fl_Chart(15, 70, 830, 360, "Spectra");
      chart->box(FL_UP_BOX);
      chart->color((Fl_Color)55);
      chart->selection_color(FL_BACKGROUND_COLOR);
      chart->labeltype(FL_NORMAL_LABEL);
      chart->labelfont(0);
      chart->labelsize(14);
      chart->labelcolor(FL_FOREGROUND_COLOR);
      chart->align(Fl_Align(FL_ALIGN_TOP));
      chart->when(FL_WHEN_RELEASE);
    } // Fl_Chart* chart
    { Fl_Button* o = new Fl_Button(15, 25, 245, 40, "Start");
      o->color((Fl_Color)61);
      o->labelfont(1);
      o->labelsize(18);
      o->callback((Fl_Callback*)cb_Start);
    } // Fl_Button* o
    specWindow->end();
  } // Fl_Double_Window* specWindow
}

void Analyzer::show() {
  specWindow->show();
}
