// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef specChart_h
#define specChart_h
#include <FL/Fl.H>
#include <FL/Fl_Chart.H>
int process(void* gui); 
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>

class Analyzer {
public:
  Analyzer();
  Fl_Double_Window *specWindow;
  Fl_Chart *chart;
private:
  inline void cb_Start_i(Fl_Button*, void*);
  static void cb_Start(Fl_Button*, void*);
public:
  void show();
};
#endif
